language:
    - cpp
sudo: required

matrix:
  include:
    # linux with gcc default (4.8)
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - ./.ci/install-deps.sh

before_script:

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
    - sudo make install
# run very basic tests
    - .ci/test_run.sh

branches:
  only:
    - /.*/

notifications:
  email: false
